logging:
  level:
    root: INFO
server:
  port: 8888

spring.boot.admin:
  probed-endpoints: health,env,metrics,httptrace:trace,httptrace,threaddump:dump,threaddump,jolokia,info,refresh,flyway,liquibase,heapdump,loggers,auditevents,mappings,scheduledtasks,configprops,caches,beans
  ui:
    cache.no-cache: true
    extension-resource-locations: "file:../azure-spring-apps-launcher/target/dist/"
    cache-templates: false
    title: Azure Spring Apps Launcher

logging.level:
  root: info
  de.codecentric: debug

asa:
#  subscription-id: 8c81302b-c67a-494e-ac1b-17e93b7e2e5a
  subscription-id: 799c12ba-353c-44a1-883d-84808ebb2216
  resource-group: rg-666
  instance-name: asa-test1
